FROM apache/airflow:2.8.1

# Switch to the root user to install system software
USER root

# Update the package list and install OpenJDK 17 (Java 17 or 11 is recommended for Spark 3.5)
RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jre-headless && \
    apt-get autoremove -yqq --purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

# Switch back to the airflow user
USER airflow

# Install Python package pyspark 3.5.0 #To match with Spark-master and worker 3.5.3
RUN pip install pyspark==3.5.3
